CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    website VARCHAR NOT NULL,
    username VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    iv VARCHAR NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)